-- このSQLファイルは自作の他MODに対して本MODの仕様に合わせこむ処理を行っている。
-- 
-- Update文やDelete文はキーがなければ更新されずに終わるが、INSERT文はキーがなければエラーになる。
-- これを回避するにはWHERE EXISTSを用いてキーとなるものが存在する場合のみINSERTという形にしなければならない。
-- XMLではそのような記述はできないと思われるのでSQL直書きにしている。

-- ========== 03 長門/陸奥/大鳳 ==========
-- 長門型戦艦の性能変更(超弩級戦艦ベースにする)
UPDATE Units
SET Cost = 620, Combat = 77, RangedCombat = 87, AntiAirCombat = 105, Maintenance = 7, StrategicResource = 'RESOURCE_OIL', PrereqTech='TECH_ADVANCED_BALLISTICS', Description = 'LOC_UNIT_UNIQUE_BATTLESHIP_NAGATO_HAGA_DESCRIPTION'
WHERE UnitType = 'UNIT_UNIQUE_BATTLESHIP_NAGATO';

UPDATE UnitReplaces
SET ReplacesUnitType = 'UNIT_HAGA_SUPER_DREDNOUGHTS'
WHERE CivUniqueUnitType = 'UNIT_UNIQUE_BATTLESHIP_NAGATO';

UPDATE Units_XP2
SET ResourceMaintenanceType = 'RESOURCE_OIL'
WHERE UnitType = 'UNIT_UNIQUE_BATTLESHIP_NAGATO';

DELETE FROM UnitUpgrades
WHERE Unit = 'UNIT_UNIQUE_BATTLESHIP_NAGATO';

INSERT INTO TypeTags('Type', 'Tag')
SELECT * FROM (SELECT 'UNIT_UNIQUE_BATTLESHIP_NAGATO', 'CLASS_HAGA_ANTI_DEF_DISTRICTS') AS TMP
WHERE EXISTS (SELECT Type FROM Types WHERE Type = 'UNIT_UNIQUE_BATTLESHIP_NAGATO');

-- ながと型ミサイル護衛艦の性能変更(本MOD仕様のミサイル巡洋艦ベースにする)
UPDATE Units
SET Range = 4
WHERE UnitType = 'UNIT_UNIQUE_MISSILE_CRUISER_NAGATO';

INSERT INTO TypeTags('Type', 'Tag')
SELECT * FROM (SELECT 'UNIT_UNIQUE_MISSILE_CRUISER_NAGATO', 'CLASS_HAGA_ANTI_NAVAL_MELEE') AS TMP
WHERE EXISTS (SELECT Type FROM Types WHERE Type = 'UNIT_UNIQUE_MISSILE_CRUISER_NAGATO');

-- 大鳳型航空母艦の性能変更、アップグレード先設定 --
UPDATE Units
SET RangedCombat = 68, Range = 2
WHERE UnitType = 'UNIT_UNIQUE_AIRCRAFT_CARRIER_TAIHO';

INSERT INTO UnitUpgrades('Unit', 'UpgradeUnit')
SELECT * FROM (SELECT 'UNIT_UNIQUE_AIRCRAFT_CARRIER_TAIHO', 'UNIT_HAGA_CVN') AS TMP
WHERE EXISTS (SELECT Type FROM Types WHERE Type ='UNIT_UNIQUE_AIRCRAFT_CARRIER_TAIHO');

-- ========== 04 港湾棲姫 ==========
-- 深海装甲巡洋艦の性能変更(本MOD仕様の装甲艦ベースにする)
UPDATE Units
SET Combat = 58, RangedCombat = 63, Range = 2, PromotionClass = 'PROMOTION_CLASS_NAVAL_RANGED'
WHERE UnitType = 'UNIT_YNL_ARMORED_CRUISER';

UPDATE UnitAiInfos
SET AiType = 'UNITTYPE_RANGED'
WHERE UnitType = 'UNIT_YNL_ARMORED_CRUISER' AND AiType = 'UNITTYPE_MELEE';

DELETE FROM UnitAiInfos
WHERE UnitType = 'UNIT_YNL_ARMORED_CRUISER' AND AiType = 'UNITAI_EXPLORE';

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_YNL_ARMORED_CRUISER', 'CLASS_HAGA_ANTI_NAVAL_MELEE') AS TMP
WHERE EXISTS (SELECT Type FROM Types WHERE Type = 'UNIT_YNL_ARMORED_CRUISER');

-- ========== 07 あきつ丸 ==========
-- カ号観測機の射程延長を戦列艦、装甲艦、巡洋艦、超弩級戦艦に適用させる
INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_LINESHIP', 'CLASS_FORWARD_KAGOU1') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU1');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_IRONCLAD', 'CLASS_FORWARD_KAGOU1') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU1');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_CRUISER', 'CLASS_FORWARD_KAGOU1') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU1');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_SUPER_DREDNOUGHTS', 'CLASS_FORWARD_KAGOU1') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU1');

-- カ号観測機の対潜+9をコルベット、戦列艦、巡洋艦、超弩級戦艦に適用させる
INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_CORVETTE', 'CLASS_FORWARD_KAGOU2') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU2');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_LINESHIP', 'CLASS_FORWARD_KAGOU2') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU2');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_CRUISER', 'CLASS_FORWARD_KAGOU2') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU2');

INSERT INTO TypeTags('Type','Tag')
SELECT * FROM (SELECT 'UNIT_HAGA_SUPER_DREDNOUGHTS', 'CLASS_FORWARD_KAGOU2') AS TMP
WHERE EXISTS (SELECT Tag FROM Tags WHERE Tag = 'CLASS_FORWARD_KAGOU2');
