-- ドラマティックモード対応
-- モードを有効にしてゲームを開始すると、ユーザーMODよりも先に公式DLCの中身がドラマティックモード用ファイルも含めて読み込まれる。
-- これによりTraytTypeからTRAIT_CIVILIZATION_GOLDEN_AGE_QUESTSが消えてしまうため、XMLではINSERTエラーになってしまう。
-- EXISTS句付きのINSERT文にすることによりエラーになるのを回避。

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_BONUS_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_LUXURY_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_STRATEGIC_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

-- ヘタイロイのバグfix(公式DLCに対する修正だが、SQLのほうが都合がいいのでここに記述)
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES('MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', 'UNIT_ADJACENT_TO_GREAT_GENERAL_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId, Name, Value)
VALUES('MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH', 'ModifierId', 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS');

UPDATE Modifiers
SET SubjectRequirementSetId = NULL
WHERE ModifierId = 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS';

UPDATE UnitAbilityModifiers
SET ModifierId = 'MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH'
WHERE UnitAbilityType = 'ABILITY_HETAIROI'
  AND ModifierId = 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS';
