-- ヘタイロイのバグfix(公式DLCに対する修正だが、SQLのほうが都合がいいのでここに記述)
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES('MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH', 'MODIFIER_SINGLE_UNIT_ATTACH_MODIFIER', 'UNIT_ADJACENT_TO_GREAT_GENERAL_REQUIREMENTS');

INSERT INTO ModifierArguments(ModifierId, Name, Value)
VALUES('MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH', 'ModifierId', 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS');

UPDATE Modifiers
SET SubjectRequirementSetId = NULL
WHERE ModifierId = 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS';

UPDATE UnitAbilityModifiers
SET ModifierId = 'MODIFIER_HAG_HETAIROI_GG_COMBAT_BONUS_ATTACH'
WHERE UnitAbilityType = 'ABILITY_HETAIROI'
  AND ModifierId = 'HETAIROI_GREAT_GENERAL_COMBAT_BONUS';
