-- ドラマティックモード対応
-- モードを有効にしてゲームを開始すると、ユーザーMODよりも先に公式DLCの中身がドラマティックモード用ファイルも含めて読み込まれる。
-- これによりTraytTypeからTRAIT_CIVILIZATION_GOLDEN_AGE_QUESTSが消えてしまうため、XMLではINSERTエラーになってしまう。
-- EXISTS句付きのINSERT文にすることによりエラーになるのを回避。

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_BONUS_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_LUXURY_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

INSERT INTO TraitModifiers('TraitType', 'ModifierId')
SELECT * FROM (SELECT 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'TRAIT_STRATEGIC_MINE_FAITH_HAGA') AS TMP
WHERE EXISTS (SELECT TraitType FROM Traits WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');
